-- Base schema required by subsequent migrations.
-- Safe for existing environments because everything is IF NOT EXISTS.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  full_name text,
  organization text,
  csr_num text,
  notes text,
  role_id uuid references public.roles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists users_email_idx on public.users (email);
create index if not exists users_role_id_idx on public.users (role_id);

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
      and t.typname = 'status'
  ) then
    create type public.status as enum ('uploaded', 'in_progress', 'complete');
  end if;
end $$;

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (user_id) on delete cascade,
  transcript_name text not null,
  transcript_path text,
  transcript_size bigint,
  due_date date not null,
  status public.status not null default 'uploaded',
  ready_date date,
  errata_path text,
  errata_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists jobs_user_id_idx on public.jobs (user_id);
create index if not exists jobs_status_idx on public.jobs (status);
create index if not exists jobs_created_at_idx on public.jobs (created_at desc);
